/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FesyaRouteImport } from './routes/fesya'
import { Route as FeswaRouteImport } from './routes/feswa'
import { Route as FeaRouteImport } from './routes/fea'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutFounderRouteImport } from './routes/about-founder'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FesyaRoute = FesyaRouteImport.update({
  id: '/fesya',
  path: '/fesya',
  getParentRoute: () => rootRouteImport,
} as any)
const FeswaRoute = FeswaRouteImport.update({
  id: '/feswa',
  path: '/feswa',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaRoute = FeaRouteImport.update({
  id: '/fea',
  path: '/fea',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFounderRoute = AboutFounderRouteImport.update({
  id: '/about-founder',
  path: '/about-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-founder': typeof AboutFounderRoute
  '/contact': typeof ContactRoute
  '/fea': typeof FeaRoute
  '/feswa': typeof FeswaRoute
  '/fesya': typeof FesyaRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/set-password': typeof SetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-founder': typeof AboutFounderRoute
  '/contact': typeof ContactRoute
  '/fea': typeof FeaRoute
  '/feswa': typeof FeswaRoute
  '/fesya': typeof FesyaRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/set-password': typeof SetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-founder': typeof AboutFounderRoute
  '/contact': typeof ContactRoute
  '/fea': typeof FeaRoute
  '/feswa': typeof FeswaRoute
  '/fesya': typeof FesyaRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-founder'
    | '/contact'
    | '/fea'
    | '/feswa'
    | '/fesya'
    | '/login'
    | '/membership'
    | '/set-password'
    | '/account'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-founder'
    | '/contact'
    | '/fea'
    | '/feswa'
    | '/fesya'
    | '/login'
    | '/membership'
    | '/set-password'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-founder'
    | '/contact'
    | '/fea'
    | '/feswa'
    | '/fesya'
    | '/login'
    | '/membership'
    | '/set-password'
    | '/_authenticated/account'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutFounderRoute: typeof AboutFounderRoute
  ContactRoute: typeof ContactRoute
  FeaRoute: typeof FeaRoute
  FeswaRoute: typeof FeswaRoute
  FesyaRoute: typeof FesyaRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fesya': {
      id: '/fesya'
      path: '/fesya'
      fullPath: '/fesya'
      preLoaderRoute: typeof FesyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feswa': {
      id: '/feswa'
      path: '/feswa'
      fullPath: '/feswa'
      preLoaderRoute: typeof FeswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fea': {
      id: '/fea'
      path: '/fea'
      fullPath: '/fea'
      preLoaderRoute: typeof FeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-founder': {
      id: '/about-founder'
      path: '/about-founder'
      fullPath: '/about-founder'
      preLoaderRoute: typeof AboutFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutFounderRoute: AboutFounderRoute,
  ContactRoute: ContactRoute,
  FeaRoute: FeaRoute,
  FeswaRoute: FeswaRoute,
  FesyaRoute: FesyaRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
