/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FesyaRouteImport } from './routes/fesya'
import { Route as FeswaRouteImport } from './routes/feswa'
import { Route as FeaRouteImport } from './routes/fea'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutFounderRouteImport } from './routes/about-founder'
import { Route as IndexRouteImport } from './routes/index'

const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FesyaRoute = FesyaRouteImport.update({
  id: '/fesya',
  path: '/fesya',
  getParentRoute: () => rootRouteImport,
} as any)
const FeswaRoute = FeswaRouteImport.update({
  id: '/feswa',
  path: '/feswa',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaRoute = FeaRouteImport.update({
  id: '/fea',
  path: '/fea',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFounderRoute = AboutFounderRouteImport.update({
  id: '/about-founder',
  path: '/about-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-founder': typeof AboutFounderRoute
  '/contact': typeof ContactRoute
  '/fea': typeof FeaRoute
  '/feswa': typeof FeswaRoute
  '/fesya': typeof FesyaRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-founder': typeof AboutFounderRoute
  '/contact': typeof ContactRoute
  '/fea': typeof FeaRoute
  '/feswa': typeof FeswaRoute
  '/fesya': typeof FesyaRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-founder': typeof AboutFounderRoute
  '/contact': typeof ContactRoute
  '/fea': typeof FeaRoute
  '/feswa': typeof FeswaRoute
  '/fesya': typeof FesyaRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-founder'
    | '/contact'
    | '/fea'
    | '/feswa'
    | '/fesya'
    | '/login'
    | '/membership'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-founder'
    | '/contact'
    | '/fea'
    | '/feswa'
    | '/fesya'
    | '/login'
    | '/membership'
  id:
    | '__root__'
    | '/'
    | '/about-founder'
    | '/contact'
    | '/fea'
    | '/feswa'
    | '/fesya'
    | '/login'
    | '/membership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutFounderRoute: typeof AboutFounderRoute
  ContactRoute: typeof ContactRoute
  FeaRoute: typeof FeaRoute
  FeswaRoute: typeof FeswaRoute
  FesyaRoute: typeof FesyaRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fesya': {
      id: '/fesya'
      path: '/fesya'
      fullPath: '/fesya'
      preLoaderRoute: typeof FesyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feswa': {
      id: '/feswa'
      path: '/feswa'
      fullPath: '/feswa'
      preLoaderRoute: typeof FeswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fea': {
      id: '/fea'
      path: '/fea'
      fullPath: '/fea'
      preLoaderRoute: typeof FeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-founder': {
      id: '/about-founder'
      path: '/about-founder'
      fullPath: '/about-founder'
      preLoaderRoute: typeof AboutFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutFounderRoute: AboutFounderRoute,
  ContactRoute: ContactRoute,
  FeaRoute: FeaRoute,
  FeswaRoute: FeswaRoute,
  FesyaRoute: FesyaRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
