// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdptnhscfcfqsyxxebml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcHRuaHNjZmNmcXN5eHhlYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxNjQ3MzYsImV4cCI6MjA5Nzc0MDczNn0.11XQs2v9NaAz5TLaA6Y_ILZgmaSDm6Tv9Ke7cCngzGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});