// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esfpbiishpkvhlejnxzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZnBiaWlzaHBrdmhsZWpueHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzMTg5ODYsImV4cCI6MjA5NTg5NDk4Nn0.XOJbyGAw9rVqMXRoeBaGuywC5GoIrDgr84Uuhhd5RUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});